version: '3'
services:
    cc_mysql:
        container_name: cc_mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_DATABASE: cc_db

    cc_tomcat:
        container_name: cc_tomcat
        build: .
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - cc_mysql
